# handlers file for postfix
---
- name: restart postfix
  command: /bin/true
  notify:
    - remove pid
    - restart service

- name: remove pid
  file:
    path: "~postfix/pid/master.pid"
    state: absent
  when: >
    (ansible_virtualization_role | default('host') == "guest")
    and (ansible_virtualization_type | default('none') == "docker")

- name: restart service
  service:
    name: postfix
    state: restarted

- name: new aliases
  command: newaliases

- name: new virtual aliases
  command: postmap /etc/postfix/virtual

- name: postmap sasl_passwd
  command: postmap hash:/etc/postfix/sasl_passwd

- name: postmap sender_canonical_maps
  command: postmap hash:/etc/postfix/sender_canonical_maps

- name: postmap generic
  command: postmap hash:/etc/postfix/generic
